text_embedder:
  qwen:
    emb_size: 3584
    max_length: 512
    checkpoint_path: "kandinsky5/weights/text_encoder/"
    
  clip:
    checkpoint_path: "kandinsky5/weights/text_encoder2/"
    emb_size: 768
    max_length: 77
